name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    tags:
      - 'v*.*.*'
      
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/ness_stretch_linux"
        token: ${{ secrets.GITHUB_TOKEN }}
