name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
  
    - uses: actions/upload-artifact@v2
      with:
        name: ness_stretch_linux
        path: /home/runner/work/ness_stretch/ness_stretch/target/release/ness_stretch
