name: Rust

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ness_stretch"
        token: ${{ secrets.GITHUB_TOKEN }}
